<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.nP5T8Xu' shared service.

return $this->privates['.service_locator.nP5T8Xu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'comentRepository' => ['privates', 'App\\Repository\\ComentRepository', 'getComentRepositoryService.php', true],
], [
    'comentRepository' => 'App\\Repository\\ComentRepository',
]);
