<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.VW4xBvb' shared service.

return $this->privates['.service_locator.VW4xBvb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'comentRepository' => ['privates', 'App\\Repository\\ComentRepository', 'getComentRepositoryService.php', true],
    'post' => ['privates', '.errored..service_locator.VW4xBvb.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.VW4xBvb": it references class "App\\Entity\\Post" but no such service exists.'],
], [
    'comentRepository' => 'App\\Repository\\ComentRepository',
    'post' => 'App\\Entity\\Post',
]);
