<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.a9cgkmL' shared service.

return $this->privates['.service_locator.a9cgkmL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\MainController::index' => ['privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true],
    'App\\Controller\\MainController::show' => ['privates', '.service_locator.nP5T8Xu', 'get_ServiceLocator_NP5T8XuService.php', true],
    'App\\Controller\\PostController::edit' => ['privates', '.service_locator.wNyQ3AI', 'get_ServiceLocator_WNyQ3AIService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SecurityController::register' => ['privates', '.service_locator.pWfxOQ_', 'get_ServiceLocator_PWfxOQService.php', true],
    'App\\Controller\\MainController:index' => ['privates', '.service_locator.jVNF2GQ', 'get_ServiceLocator_JVNF2GQService.php', true],
    'App\\Controller\\MainController:show' => ['privates', '.service_locator.nP5T8Xu', 'get_ServiceLocator_NP5T8XuService.php', true],
    'App\\Controller\\PostController:edit' => ['privates', '.service_locator.wNyQ3AI', 'get_ServiceLocator_WNyQ3AIService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\SecurityController:register' => ['privates', '.service_locator.pWfxOQ_', 'get_ServiceLocator_PWfxOQService.php', true],
], [
    'App\\Controller\\MainController::index' => '?',
    'App\\Controller\\MainController::show' => '?',
    'App\\Controller\\PostController::edit' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\SecurityController::register' => '?',
    'App\\Controller\\MainController:index' => '?',
    'App\\Controller\\MainController:show' => '?',
    'App\\Controller\\PostController:edit' => '?',
    'App\\Controller\\SecurityController:login' => '?',
    'App\\Controller\\SecurityController:register' => '?',
]);
