<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.wNyQ3AI' shared service.

return $this->privates['.service_locator.wNyQ3AI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'uploaderHelper' => ['privates', 'App\\Service\\UploaderHelper', NULL, 'Cannot autowire service "App\\Service\\UploaderHelper": argument "$uploadsPath" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
], [
    'uploaderHelper' => 'App\\Service\\UploaderHelper',
]);
