<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTbxgTJr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTbxgTJr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTbxgTJr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTbxgTJr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTbxgTJr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TbxgTJr',
    'container.build_id' => '45c07209',
    'container.build_time' => 1574630418,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTbxgTJr');
