<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXjA7Dxz\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXjA7Dxz/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXjA7Dxz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXjA7Dxz\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXjA7Dxz\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XjA7Dxz',
    'container.build_id' => '6ff3164e',
    'container.build_time' => 1574618333,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXjA7Dxz');
