<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCrhcwqs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCrhcwqs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCrhcwqs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCrhcwqs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCrhcwqs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Crhcwqs',
    'container.build_id' => '7083d562',
    'container.build_time' => 1574429814,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCrhcwqs');
